### ISSUE TITLE
Error on base_address casting

### ISSUE THREAD

**Issue by diegoc9310** [Microsoft/pmwcas#6]
Issue in the casting of the base address.
uintptr_t base_address = *(uintptr_t*)((uintptr_t)segment->GetMapAddress() + sizeof(uint64_t));
in order to behave appropriately after re-run of benchmark on the same mwcas_server it should be changed

**Comment by wangtzh** [comment]
IIRC this is deliberate to avoid changing all pointers across runs. There should be an assertion (didn't check, but should be in the server code) that checks for the address returned by mmap. If they don't match it won't continue. Hope this clarifies.

**Comment by wangtzh** [comment]
Closing since there are no new updates.
