### ISSUE TITLE
Allocate(void **mem, size_t size)

### ISSUE THREAD

**Issue by UnlimitedChild** [Microsoft/pmwcas#9]
Hi,

there are several errors in the project that do not allow you to compile test samples in Visual Studio 2019.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error (active)	E0171	invalid type conversion	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	286	
> Error (active)	E0167	argument of type "unsigned long long" is incompatible with parameter of type "void **"	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	287	
> Error (active)	E0165	too few arguments in function call	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	287	
> Error (active)	E0322	object of abstract class type "pmwcas::DefaultAllocator" is not allowed:	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	442	
> Error (active)	E0461	initial value of reference to non-const must be an lvalue	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	632	
> Error (active)	E0322	object of abstract class type "pmwcas::TlsAllocator" is not allowed:	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	675	
> Error (active)	E0461	initial value of reference to non-const must be an lvalue	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	705

	

**environment_windows.h**
`BlockingIOContext* io_context = reinterpret_cast<BlockingIOContext*>(
          allocator->Allocate(sizeof(BlockingIOContext)));
      if(!io_context) return Status::OutOfMemory();
      unique_ptr_t<BlockingIOContext> context_guard(
      io_context, [=](BlockingIOContext* c) {
        allocator->Free(c);
      });`

`namespace pmwcas {

/// Interface for custom memory allocator plug-in. The PMwCAS library does not1
/// assume a particular allocator, and will use whatever is behind IAllocator to
/// allocate memory. See pmwcas::InitLibrary in /include/pmwcas.h.
class IAllocator {
 public:
  **virtual void Allocate(void **mem, size_t size) = 0;**
  virtual void AllocateAligned(void **mem, size_t size, uint32_t alignment) = 0;
  virtual void AllocateAlignedOffset(void **mem, size_t size, size_t alignment,
                                     size_t offset) = 0;
  virtual void AllocateHuge(void **mem, size_t size) = 0;
  virtual void CAlloc(void **mem, size_t count, size_t size) = 0;
  virtual void Free(void* bytes) = 0;
  virtual void FreeAligned(void* bytes) = 0;
  virtual uint64_t GetAllocatedSize(void* bytes) = 0;
  virtual Status Validate(void* bytes) = 0;
};

} // namespace pmwcas
`

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2660	'pmwcas::IAllocator::Allocate': function does not take 1 arguments	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	285	
Error	C2259	'pmwcas::DefaultAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	440	
Error	C2259	'pmwcas::DefaultAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	440	
Error	C2440	'initializing': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>' to 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>> &'	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	629	
Error	C2259	'pmwcas::TlsAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	672	
Error	C2259	'pmwcas::TlsAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	672	
Error	C2440	'initializing': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>' to 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>> &'	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	702	
Error	C2660	'pmwcas::IAllocator::Allocate': function does not take 1 arguments	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	285	
Error	C2259	'pmwcas::DefaultAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	440	
Error	C2259	'pmwcas::DefaultAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	440	
Error	C2440	'initializing': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>' to 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>> &'	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	629	
Error	C2259	'pmwcas::TlsAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	672	
Error	C2259	'pmwcas::TlsAllocator': cannot instantiate abstract class	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	672	
Error	C2440	'initializing': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>' to 'std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>> &'	FreeLockDouble	E:\DATA\MASM64\Kip Irvine 2016 Assembler x64\Queue - A Lock Free Doubly Linked List\Persistent Multi-Word Compare-and-Swap (PMwCAS) for NVRAM\DoubleLFree\FreeLockDouble\FreeLockDouble\environment\environment_windows.h	702	
`
[FreeLockDouble.zip](https://github.com/microsoft/pmwcas/files/4376870/FreeLockDouble.zip)

**Comment by wangtzh** [comment]
The current latest version focused only on Linux build, including integration with PMDK and new fixes. We recommend using Linux. Probably you will have to checkout an older version if you need a Windows build (without PMDK allocator support).

**Comment by UnlimitedChild** [comment]
> The current latest version focused only on Linux build, including integration with PMDK and new fixes. We recommend using Linux. Probably you will have to checkout an older version if you need a Windows build (without PMDK allocator support).

Thanks, where can I download the previous version for windows?

**Comment by wangtzh** [comment]
You can try the initial commit from this repo. But note that it won't work directly on real Optane DCPMM.

**Comment by wangtzh** [comment]
Closing this issue for now.
